apiVersion: apps/v1
kind: Deployment
metadata: 
  name: queryz-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queryz
  template:
    metadata:
      labels:
        app: queryz
    spec:
      containers:
        - name: queryz
          image: mhkh/queryz:latest
---
apiVersion: v1
kind: Service
metadata:
  name: queryz-srv
spec:
  selector:
    app: queryz
  ports: 
    - name: queryz
      protocol: TCP
      port: 4002
      targetPort: 4002